# Generated by Django 4.0.4 on 2022-05-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.ManyToManyField(related_name='gamers', to='levelupapi.gamer'),
        ),
    ]
